//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CacheNomAdministration.SoapServices.SoapProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ControlPointView", Namespace="http://tempuri.org")]
    [System.SerializableAttribute()]
    public partial class ControlPointView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string TotalizerTagField;
        
        private long ControlPointIDField;
        
        private long FlowDirectionField;
        
        private long ControlerCodeField;
        
        private long PositionNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ControlPointNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EngineeringUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string TotalizerTag {
            get {
                return this.TotalizerTagField;
            }
            set {
                if ((object.ReferenceEquals(this.TotalizerTagField, value) != true)) {
                    this.TotalizerTagField = value;
                    this.RaisePropertyChanged("TotalizerTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public long ControlPointID {
            get {
                return this.ControlPointIDField;
            }
            set {
                if ((this.ControlPointIDField.Equals(value) != true)) {
                    this.ControlPointIDField = value;
                    this.RaisePropertyChanged("ControlPointID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public long FlowDirection {
            get {
                return this.FlowDirectionField;
            }
            set {
                if ((this.FlowDirectionField.Equals(value) != true)) {
                    this.FlowDirectionField = value;
                    this.RaisePropertyChanged("FlowDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public long ControlerCode {
            get {
                return this.ControlerCodeField;
            }
            set {
                if ((this.ControlerCodeField.Equals(value) != true)) {
                    this.ControlerCodeField = value;
                    this.RaisePropertyChanged("ControlerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public long PositionNumber {
            get {
                return this.PositionNumberField;
            }
            set {
                if ((this.PositionNumberField.Equals(value) != true)) {
                    this.PositionNumberField = value;
                    this.RaisePropertyChanged("PositionNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ControlPointName {
            get {
                return this.ControlPointNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ControlPointNameField, value) != true)) {
                    this.ControlPointNameField = value;
                    this.RaisePropertyChanged("ControlPointName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string EngineeringUnit {
            get {
                return this.EngineeringUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.EngineeringUnitField, value) != true)) {
                    this.EngineeringUnitField = value;
                    this.RaisePropertyChanged("EngineeringUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ProductCode {
            get {
                return this.ProductCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCodeField, value) != true)) {
                    this.ProductCodeField = value;
                    this.RaisePropertyChanged("ProductCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfTotalizatorTagControlPointTotalizatorTagControlPoint", Namespace="http://tempuri.org", ItemName="TotalizatorTagControlPoint")]
    [System.SerializableAttribute()]
    public class ArrayOfTotalizatorTagControlPointTotalizatorTagControlPoint : System.Collections.Generic.List<CacheNomAdministration.SoapServices.SoapProxy.TotalizatorTagControlPoint> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TotalizatorTagControlPoint", Namespace="http://tempuri.org")]
    [System.SerializableAttribute()]
    public partial class TotalizatorTagControlPoint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string TotalizerTagField;
        
        private long ControlPointIDField;
        
        private long FlowDirectionField;
        
        private long ControlerCodeField;
        
        private long PositionNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ControlPointNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EngineeringUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string TotalizerTag {
            get {
                return this.TotalizerTagField;
            }
            set {
                if ((object.ReferenceEquals(this.TotalizerTagField, value) != true)) {
                    this.TotalizerTagField = value;
                    this.RaisePropertyChanged("TotalizerTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public long ControlPointID {
            get {
                return this.ControlPointIDField;
            }
            set {
                if ((this.ControlPointIDField.Equals(value) != true)) {
                    this.ControlPointIDField = value;
                    this.RaisePropertyChanged("ControlPointID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public long FlowDirection {
            get {
                return this.FlowDirectionField;
            }
            set {
                if ((this.FlowDirectionField.Equals(value) != true)) {
                    this.FlowDirectionField = value;
                    this.RaisePropertyChanged("FlowDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public long ControlerCode {
            get {
                return this.ControlerCodeField;
            }
            set {
                if ((this.ControlerCodeField.Equals(value) != true)) {
                    this.ControlerCodeField = value;
                    this.RaisePropertyChanged("ControlerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public long PositionNumber {
            get {
                return this.PositionNumberField;
            }
            set {
                if ((this.PositionNumberField.Equals(value) != true)) {
                    this.PositionNumberField = value;
                    this.RaisePropertyChanged("PositionNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ControlPointName {
            get {
                return this.ControlPointNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ControlPointNameField, value) != true)) {
                    this.ControlPointNameField = value;
                    this.RaisePropertyChanged("ControlPointName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string EngineeringUnit {
            get {
                return this.EngineeringUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.EngineeringUnitField, value) != true)) {
                    this.EngineeringUnitField = value;
                    this.RaisePropertyChanged("EngineeringUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ProductCode {
            get {
                return this.ProductCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCodeField, value) != true)) {
                    this.ProductCodeField = value;
                    this.RaisePropertyChanged("ProductCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfMeasuringPointsMeasuringPoints", Namespace="http://tempuri.org", ItemName="MeasuringPoints")]
    [System.SerializableAttribute()]
    public class ArrayOfMeasuringPointsMeasuringPoints : System.Collections.Generic.List<CacheNomAdministration.SoapServices.SoapProxy.MeasuringPoints> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MeasuringPoints", Namespace="http://tempuri.org")]
    [System.SerializableAttribute()]
    public partial class MeasuringPoints : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long MeasuringPointIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeasuringPointNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ControlPointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ZoneIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long FlowDirectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortControlPointNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long MeasuringPointId {
            get {
                return this.MeasuringPointIdField;
            }
            set {
                if ((this.MeasuringPointIdField.Equals(value) != true)) {
                    this.MeasuringPointIdField = value;
                    this.RaisePropertyChanged("MeasuringPointId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MeasuringPointName {
            get {
                return this.MeasuringPointNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MeasuringPointNameField, value) != true)) {
                    this.MeasuringPointNameField = value;
                    this.RaisePropertyChanged("MeasuringPointName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ControlPoint {
            get {
                return this.ControlPointField;
            }
            set {
                if ((object.ReferenceEquals(this.ControlPointField, value) != true)) {
                    this.ControlPointField = value;
                    this.RaisePropertyChanged("ControlPoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long ZoneId {
            get {
                return this.ZoneIdField;
            }
            set {
                if ((this.ZoneIdField.Equals(value) != true)) {
                    this.ZoneIdField = value;
                    this.RaisePropertyChanged("ZoneId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long FlowDirection {
            get {
                return this.FlowDirectionField;
            }
            set {
                if ((this.FlowDirectionField.Equals(value) != true)) {
                    this.FlowDirectionField = value;
                    this.RaisePropertyChanged("FlowDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ShortControlPointName {
            get {
                return this.ShortControlPointNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortControlPointNameField, value) != true)) {
                    this.ShortControlPointNameField = value;
                    this.RaisePropertyChanged("ShortControlPointName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="SoapProxy.ManagementNomenclaturesSoap")]
    public interface ManagementNomenclaturesSoap {
        
        // CODEGEN: Generating message contract since element name totalizertag from namespace http://tempuri.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManagementNomenclatures.ManagementNomenclatures.AddRecord", ReplyAction="*")]
        CacheNomAdministration.SoapServices.SoapProxy.AddRecordResponse AddRecord(CacheNomAdministration.SoapServices.SoapProxy.AddRecordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManagementNomenclatures.ManagementNomenclatures.AddRecord", ReplyAction="*")]
        System.Threading.Tasks.Task<CacheNomAdministration.SoapServices.SoapProxy.AddRecordResponse> AddRecordAsync(CacheNomAdministration.SoapServices.SoapProxy.AddRecordRequest request);
        
        // CODEGEN: Generating message contract since element name tag from namespace http://tempuri.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManagementNomenclatures.ManagementNomenclatures.DeleteRecordTa" +
            "g", ReplyAction="*")]
        CacheNomAdministration.SoapServices.SoapProxy.DeleteRecordTagResponse DeleteRecordTag(CacheNomAdministration.SoapServices.SoapProxy.DeleteRecordTagRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManagementNomenclatures.ManagementNomenclatures.DeleteRecordTa" +
            "g", ReplyAction="*")]
        System.Threading.Tasks.Task<CacheNomAdministration.SoapServices.SoapProxy.DeleteRecordTagResponse> DeleteRecordTagAsync(CacheNomAdministration.SoapServices.SoapProxy.DeleteRecordTagRequest request);
        
        // CODEGEN: Generating message contract since element name GetConfigurationResult from namespace http://tempuri.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManagementNomenclatures.ManagementNomenclatures.GetConfigurati" +
            "on", ReplyAction="*")]
        CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationResponse GetConfiguration(CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManagementNomenclatures.ManagementNomenclatures.GetConfigurati" +
            "on", ReplyAction="*")]
        System.Threading.Tasks.Task<CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationResponse> GetConfigurationAsync(CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationRequest request);
        
        // CODEGEN: Generating message contract since element name GetConfigurationIdResult from namespace http://tempuri.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManagementNomenclatures.ManagementNomenclatures.GetConfigurati" +
            "onId", ReplyAction="*")]
        CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationIdResponse GetConfigurationId(CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManagementNomenclatures.ManagementNomenclatures.GetConfigurati" +
            "onId", ReplyAction="*")]
        System.Threading.Tasks.Task<CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationIdResponse> GetConfigurationIdAsync(CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationIdRequest request);
        
        // CODEGEN: Generating message contract since element name GetIdControlPointResult from namespace http://tempuri.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManagementNomenclatures.ManagementNomenclatures.GetIdControlPo" +
            "int", ReplyAction="*")]
        CacheNomAdministration.SoapServices.SoapProxy.GetIdControlPointResponse GetIdControlPoint(CacheNomAdministration.SoapServices.SoapProxy.GetIdControlPointRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManagementNomenclatures.ManagementNomenclatures.GetIdControlPo" +
            "int", ReplyAction="*")]
        System.Threading.Tasks.Task<CacheNomAdministration.SoapServices.SoapProxy.GetIdControlPointResponse> GetIdControlPointAsync(CacheNomAdministration.SoapServices.SoapProxy.GetIdControlPointRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManagementNomenclatures.ManagementNomenclatures.IsValidControl" +
            "PointID", ReplyAction="*")]
        bool IsValidControlPointID(long controlpointid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManagementNomenclatures.ManagementNomenclatures.IsValidControl" +
            "PointID", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> IsValidControlPointIDAsync(long controlpointid);
        
        // CODEGEN: Generating message contract since element name controlpointname from namespace http://tempuri.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManagementNomenclatures.ManagementNomenclatures.IsValidControl" +
            "PointName", ReplyAction="*")]
        CacheNomAdministration.SoapServices.SoapProxy.IsValidControlPointNameResponse IsValidControlPointName(CacheNomAdministration.SoapServices.SoapProxy.IsValidControlPointNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManagementNomenclatures.ManagementNomenclatures.IsValidControl" +
            "PointName", ReplyAction="*")]
        System.Threading.Tasks.Task<CacheNomAdministration.SoapServices.SoapProxy.IsValidControlPointNameResponse> IsValidControlPointNameAsync(CacheNomAdministration.SoapServices.SoapProxy.IsValidControlPointNameRequest request);
        
        // CODEGEN: Generating message contract since element name productcode from namespace http://tempuri.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManagementNomenclatures.ManagementNomenclatures.IsValidProduct" +
            "Code", ReplyAction="*")]
        CacheNomAdministration.SoapServices.SoapProxy.IsValidProductCodeResponse IsValidProductCode(CacheNomAdministration.SoapServices.SoapProxy.IsValidProductCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManagementNomenclatures.ManagementNomenclatures.IsValidProduct" +
            "Code", ReplyAction="*")]
        System.Threading.Tasks.Task<CacheNomAdministration.SoapServices.SoapProxy.IsValidProductCodeResponse> IsValidProductCodeAsync(CacheNomAdministration.SoapServices.SoapProxy.IsValidProductCodeRequest request);
        
        // CODEGEN: Generating message contract since element name TestResult from namespace http://tempuri.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManagementNomenclatures.ManagementNomenclatures.Test", ReplyAction="*")]
        CacheNomAdministration.SoapServices.SoapProxy.TestResponse Test(CacheNomAdministration.SoapServices.SoapProxy.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManagementNomenclatures.ManagementNomenclatures.Test", ReplyAction="*")]
        System.Threading.Tasks.Task<CacheNomAdministration.SoapServices.SoapProxy.TestResponse> TestAsync(CacheNomAdministration.SoapServices.SoapProxy.TestRequest request);
        
        // CODEGEN: Generating message contract since element name tag from namespace http://tempuri.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManagementNomenclatures.ManagementNomenclatures.UpdateRecordTa" +
            "g", ReplyAction="*")]
        CacheNomAdministration.SoapServices.SoapProxy.UpdateRecordTagResponse UpdateRecordTag(CacheNomAdministration.SoapServices.SoapProxy.UpdateRecordTagRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManagementNomenclatures.ManagementNomenclatures.UpdateRecordTa" +
            "g", ReplyAction="*")]
        System.Threading.Tasks.Task<CacheNomAdministration.SoapServices.SoapProxy.UpdateRecordTagResponse> UpdateRecordTagAsync(CacheNomAdministration.SoapServices.SoapProxy.UpdateRecordTagRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRecordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRecord", Namespace="http://tempuri.org", Order=0)]
        public CacheNomAdministration.SoapServices.SoapProxy.AddRecordRequestBody Body;
        
        public AddRecordRequest() {
        }
        
        public AddRecordRequest(CacheNomAdministration.SoapServices.SoapProxy.AddRecordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class AddRecordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CacheNomAdministration.SoapServices.SoapProxy.ControlPointView totalizertag;
        
        public AddRecordRequestBody() {
        }
        
        public AddRecordRequestBody(CacheNomAdministration.SoapServices.SoapProxy.ControlPointView totalizertag) {
            this.totalizertag = totalizertag;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRecordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRecordResponse", Namespace="http://tempuri.org", Order=0)]
        public CacheNomAdministration.SoapServices.SoapProxy.AddRecordResponseBody Body;
        
        public AddRecordResponse() {
        }
        
        public AddRecordResponse(CacheNomAdministration.SoapServices.SoapProxy.AddRecordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class AddRecordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddRecordResult;
        
        public AddRecordResponseBody() {
        }
        
        public AddRecordResponseBody(string AddRecordResult) {
            this.AddRecordResult = AddRecordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRecordTagRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteRecordTag", Namespace="http://tempuri.org", Order=0)]
        public CacheNomAdministration.SoapServices.SoapProxy.DeleteRecordTagRequestBody Body;
        
        public DeleteRecordTagRequest() {
        }
        
        public DeleteRecordTagRequest(CacheNomAdministration.SoapServices.SoapProxy.DeleteRecordTagRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class DeleteRecordTagRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tag;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long controlpointid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long flowdirection;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long controlecode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long positionnumber;
        
        public DeleteRecordTagRequestBody() {
        }
        
        public DeleteRecordTagRequestBody(string tag, long controlpointid, long flowdirection, long controlecode, long positionnumber) {
            this.tag = tag;
            this.controlpointid = controlpointid;
            this.flowdirection = flowdirection;
            this.controlecode = controlecode;
            this.positionnumber = positionnumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRecordTagResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteRecordTagResponse", Namespace="http://tempuri.org", Order=0)]
        public CacheNomAdministration.SoapServices.SoapProxy.DeleteRecordTagResponseBody Body;
        
        public DeleteRecordTagResponse() {
        }
        
        public DeleteRecordTagResponse(CacheNomAdministration.SoapServices.SoapProxy.DeleteRecordTagResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class DeleteRecordTagResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteRecordTagResult;
        
        public DeleteRecordTagResponseBody() {
        }
        
        public DeleteRecordTagResponseBody(string DeleteRecordTagResult) {
            this.DeleteRecordTagResult = DeleteRecordTagResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetConfigurationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetConfiguration", Namespace="http://tempuri.org", Order=0)]
        public CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationRequestBody Body;
        
        public GetConfigurationRequest() {
        }
        
        public GetConfigurationRequest(CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetConfigurationRequestBody {
        
        public GetConfigurationRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetConfigurationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetConfigurationResponse", Namespace="http://tempuri.org", Order=0)]
        public CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationResponseBody Body;
        
        public GetConfigurationResponse() {
        }
        
        public GetConfigurationResponse(CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class GetConfigurationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CacheNomAdministration.SoapServices.SoapProxy.ArrayOfTotalizatorTagControlPointTotalizatorTagControlPoint GetConfigurationResult;
        
        public GetConfigurationResponseBody() {
        }
        
        public GetConfigurationResponseBody(CacheNomAdministration.SoapServices.SoapProxy.ArrayOfTotalizatorTagControlPointTotalizatorTagControlPoint GetConfigurationResult) {
            this.GetConfigurationResult = GetConfigurationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetConfigurationIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetConfigurationId", Namespace="http://tempuri.org", Order=0)]
        public CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationIdRequestBody Body;
        
        public GetConfigurationIdRequest() {
        }
        
        public GetConfigurationIdRequest(CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class GetConfigurationIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long controlpointid;
        
        public GetConfigurationIdRequestBody() {
        }
        
        public GetConfigurationIdRequestBody(long controlpointid) {
            this.controlpointid = controlpointid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetConfigurationIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetConfigurationIdResponse", Namespace="http://tempuri.org", Order=0)]
        public CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationIdResponseBody Body;
        
        public GetConfigurationIdResponse() {
        }
        
        public GetConfigurationIdResponse(CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class GetConfigurationIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CacheNomAdministration.SoapServices.SoapProxy.ArrayOfTotalizatorTagControlPointTotalizatorTagControlPoint GetConfigurationIdResult;
        
        public GetConfigurationIdResponseBody() {
        }
        
        public GetConfigurationIdResponseBody(CacheNomAdministration.SoapServices.SoapProxy.ArrayOfTotalizatorTagControlPointTotalizatorTagControlPoint GetConfigurationIdResult) {
            this.GetConfigurationIdResult = GetConfigurationIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIdControlPointRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIdControlPoint", Namespace="http://tempuri.org", Order=0)]
        public CacheNomAdministration.SoapServices.SoapProxy.GetIdControlPointRequestBody Body;
        
        public GetIdControlPointRequest() {
        }
        
        public GetIdControlPointRequest(CacheNomAdministration.SoapServices.SoapProxy.GetIdControlPointRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetIdControlPointRequestBody {
        
        public GetIdControlPointRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIdControlPointResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIdControlPointResponse", Namespace="http://tempuri.org", Order=0)]
        public CacheNomAdministration.SoapServices.SoapProxy.GetIdControlPointResponseBody Body;
        
        public GetIdControlPointResponse() {
        }
        
        public GetIdControlPointResponse(CacheNomAdministration.SoapServices.SoapProxy.GetIdControlPointResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class GetIdControlPointResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CacheNomAdministration.SoapServices.SoapProxy.ArrayOfMeasuringPointsMeasuringPoints GetIdControlPointResult;
        
        public GetIdControlPointResponseBody() {
        }
        
        public GetIdControlPointResponseBody(CacheNomAdministration.SoapServices.SoapProxy.ArrayOfMeasuringPointsMeasuringPoints GetIdControlPointResult) {
            this.GetIdControlPointResult = GetIdControlPointResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsValidControlPointNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsValidControlPointName", Namespace="http://tempuri.org", Order=0)]
        public CacheNomAdministration.SoapServices.SoapProxy.IsValidControlPointNameRequestBody Body;
        
        public IsValidControlPointNameRequest() {
        }
        
        public IsValidControlPointNameRequest(CacheNomAdministration.SoapServices.SoapProxy.IsValidControlPointNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class IsValidControlPointNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long controlpointid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string controlpointname;
        
        public IsValidControlPointNameRequestBody() {
        }
        
        public IsValidControlPointNameRequestBody(long controlpointid, string controlpointname) {
            this.controlpointid = controlpointid;
            this.controlpointname = controlpointname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsValidControlPointNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsValidControlPointNameResponse", Namespace="http://tempuri.org", Order=0)]
        public CacheNomAdministration.SoapServices.SoapProxy.IsValidControlPointNameResponseBody Body;
        
        public IsValidControlPointNameResponse() {
        }
        
        public IsValidControlPointNameResponse(CacheNomAdministration.SoapServices.SoapProxy.IsValidControlPointNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class IsValidControlPointNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsValidControlPointNameResult;
        
        public IsValidControlPointNameResponseBody() {
        }
        
        public IsValidControlPointNameResponseBody(bool IsValidControlPointNameResult) {
            this.IsValidControlPointNameResult = IsValidControlPointNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsValidProductCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsValidProductCode", Namespace="http://tempuri.org", Order=0)]
        public CacheNomAdministration.SoapServices.SoapProxy.IsValidProductCodeRequestBody Body;
        
        public IsValidProductCodeRequest() {
        }
        
        public IsValidProductCodeRequest(CacheNomAdministration.SoapServices.SoapProxy.IsValidProductCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class IsValidProductCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string productcode;
        
        public IsValidProductCodeRequestBody() {
        }
        
        public IsValidProductCodeRequestBody(string productcode) {
            this.productcode = productcode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsValidProductCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsValidProductCodeResponse", Namespace="http://tempuri.org", Order=0)]
        public CacheNomAdministration.SoapServices.SoapProxy.IsValidProductCodeResponseBody Body;
        
        public IsValidProductCodeResponse() {
        }
        
        public IsValidProductCodeResponse(CacheNomAdministration.SoapServices.SoapProxy.IsValidProductCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class IsValidProductCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsValidProductCodeResult;
        
        public IsValidProductCodeResponseBody() {
        }
        
        public IsValidProductCodeResponseBody(bool IsValidProductCodeResult) {
            this.IsValidProductCodeResult = IsValidProductCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Test", Namespace="http://tempuri.org", Order=0)]
        public CacheNomAdministration.SoapServices.SoapProxy.TestRequestBody Body;
        
        public TestRequest() {
        }
        
        public TestRequest(CacheNomAdministration.SoapServices.SoapProxy.TestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestRequestBody {
        
        public TestRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestResponse", Namespace="http://tempuri.org", Order=0)]
        public CacheNomAdministration.SoapServices.SoapProxy.TestResponseBody Body;
        
        public TestResponse() {
        }
        
        public TestResponse(CacheNomAdministration.SoapServices.SoapProxy.TestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class TestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestResult;
        
        public TestResponseBody() {
        }
        
        public TestResponseBody(string TestResult) {
            this.TestResult = TestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRecordTagRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateRecordTag", Namespace="http://tempuri.org", Order=0)]
        public CacheNomAdministration.SoapServices.SoapProxy.UpdateRecordTagRequestBody Body;
        
        public UpdateRecordTagRequest() {
        }
        
        public UpdateRecordTagRequest(CacheNomAdministration.SoapServices.SoapProxy.UpdateRecordTagRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class UpdateRecordTagRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tag;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long controlpointid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long flowdirection;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long controlecode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long positionnumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string productcode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string engineeringunit;
        
        public UpdateRecordTagRequestBody() {
        }
        
        public UpdateRecordTagRequestBody(string tag, long controlpointid, long flowdirection, long controlecode, long positionnumber, string productcode, string engineeringunit) {
            this.tag = tag;
            this.controlpointid = controlpointid;
            this.flowdirection = flowdirection;
            this.controlecode = controlecode;
            this.positionnumber = positionnumber;
            this.productcode = productcode;
            this.engineeringunit = engineeringunit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRecordTagResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateRecordTagResponse", Namespace="http://tempuri.org", Order=0)]
        public CacheNomAdministration.SoapServices.SoapProxy.UpdateRecordTagResponseBody Body;
        
        public UpdateRecordTagResponse() {
        }
        
        public UpdateRecordTagResponse(CacheNomAdministration.SoapServices.SoapProxy.UpdateRecordTagResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class UpdateRecordTagResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateRecordTagResult;
        
        public UpdateRecordTagResponseBody() {
        }
        
        public UpdateRecordTagResponseBody(string UpdateRecordTagResult) {
            this.UpdateRecordTagResult = UpdateRecordTagResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ManagementNomenclaturesSoapChannel : CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManagementNomenclaturesSoapClient : System.ServiceModel.ClientBase<CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap>, CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap {
        
        public ManagementNomenclaturesSoapClient() {
        }
        
        public ManagementNomenclaturesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManagementNomenclaturesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManagementNomenclaturesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManagementNomenclaturesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CacheNomAdministration.SoapServices.SoapProxy.AddRecordResponse CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap.AddRecord(CacheNomAdministration.SoapServices.SoapProxy.AddRecordRequest request) {
            return base.Channel.AddRecord(request);
        }
        
        public string AddRecord(CacheNomAdministration.SoapServices.SoapProxy.ControlPointView totalizertag) {
            CacheNomAdministration.SoapServices.SoapProxy.AddRecordRequest inValue = new CacheNomAdministration.SoapServices.SoapProxy.AddRecordRequest();
            inValue.Body = new CacheNomAdministration.SoapServices.SoapProxy.AddRecordRequestBody();
            inValue.Body.totalizertag = totalizertag;
            CacheNomAdministration.SoapServices.SoapProxy.AddRecordResponse retVal = ((CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap)(this)).AddRecord(inValue);
            return retVal.Body.AddRecordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CacheNomAdministration.SoapServices.SoapProxy.AddRecordResponse> CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap.AddRecordAsync(CacheNomAdministration.SoapServices.SoapProxy.AddRecordRequest request) {
            return base.Channel.AddRecordAsync(request);
        }
        
        public System.Threading.Tasks.Task<CacheNomAdministration.SoapServices.SoapProxy.AddRecordResponse> AddRecordAsync(CacheNomAdministration.SoapServices.SoapProxy.ControlPointView totalizertag) {
            CacheNomAdministration.SoapServices.SoapProxy.AddRecordRequest inValue = new CacheNomAdministration.SoapServices.SoapProxy.AddRecordRequest();
            inValue.Body = new CacheNomAdministration.SoapServices.SoapProxy.AddRecordRequestBody();
            inValue.Body.totalizertag = totalizertag;
            return ((CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap)(this)).AddRecordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CacheNomAdministration.SoapServices.SoapProxy.DeleteRecordTagResponse CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap.DeleteRecordTag(CacheNomAdministration.SoapServices.SoapProxy.DeleteRecordTagRequest request) {
            return base.Channel.DeleteRecordTag(request);
        }
        
        public string DeleteRecordTag(string tag, long controlpointid, long flowdirection, long controlecode, long positionnumber) {
            CacheNomAdministration.SoapServices.SoapProxy.DeleteRecordTagRequest inValue = new CacheNomAdministration.SoapServices.SoapProxy.DeleteRecordTagRequest();
            inValue.Body = new CacheNomAdministration.SoapServices.SoapProxy.DeleteRecordTagRequestBody();
            inValue.Body.tag = tag;
            inValue.Body.controlpointid = controlpointid;
            inValue.Body.flowdirection = flowdirection;
            inValue.Body.controlecode = controlecode;
            inValue.Body.positionnumber = positionnumber;
            CacheNomAdministration.SoapServices.SoapProxy.DeleteRecordTagResponse retVal = ((CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap)(this)).DeleteRecordTag(inValue);
            return retVal.Body.DeleteRecordTagResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CacheNomAdministration.SoapServices.SoapProxy.DeleteRecordTagResponse> CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap.DeleteRecordTagAsync(CacheNomAdministration.SoapServices.SoapProxy.DeleteRecordTagRequest request) {
            return base.Channel.DeleteRecordTagAsync(request);
        }
        
        public System.Threading.Tasks.Task<CacheNomAdministration.SoapServices.SoapProxy.DeleteRecordTagResponse> DeleteRecordTagAsync(string tag, long controlpointid, long flowdirection, long controlecode, long positionnumber) {
            CacheNomAdministration.SoapServices.SoapProxy.DeleteRecordTagRequest inValue = new CacheNomAdministration.SoapServices.SoapProxy.DeleteRecordTagRequest();
            inValue.Body = new CacheNomAdministration.SoapServices.SoapProxy.DeleteRecordTagRequestBody();
            inValue.Body.tag = tag;
            inValue.Body.controlpointid = controlpointid;
            inValue.Body.flowdirection = flowdirection;
            inValue.Body.controlecode = controlecode;
            inValue.Body.positionnumber = positionnumber;
            return ((CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap)(this)).DeleteRecordTagAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationResponse CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap.GetConfiguration(CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationRequest request) {
            return base.Channel.GetConfiguration(request);
        }
        
        public CacheNomAdministration.SoapServices.SoapProxy.ArrayOfTotalizatorTagControlPointTotalizatorTagControlPoint GetConfiguration() {
            CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationRequest inValue = new CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationRequest();
            inValue.Body = new CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationRequestBody();
            CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationResponse retVal = ((CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap)(this)).GetConfiguration(inValue);
            return retVal.Body.GetConfigurationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationResponse> CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap.GetConfigurationAsync(CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationRequest request) {
            return base.Channel.GetConfigurationAsync(request);
        }
        
        public System.Threading.Tasks.Task<CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationResponse> GetConfigurationAsync() {
            CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationRequest inValue = new CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationRequest();
            inValue.Body = new CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationRequestBody();
            return ((CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap)(this)).GetConfigurationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationIdResponse CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap.GetConfigurationId(CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationIdRequest request) {
            return base.Channel.GetConfigurationId(request);
        }
        
        public CacheNomAdministration.SoapServices.SoapProxy.ArrayOfTotalizatorTagControlPointTotalizatorTagControlPoint GetConfigurationId(long controlpointid) {
            CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationIdRequest inValue = new CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationIdRequest();
            inValue.Body = new CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationIdRequestBody();
            inValue.Body.controlpointid = controlpointid;
            CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationIdResponse retVal = ((CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap)(this)).GetConfigurationId(inValue);
            return retVal.Body.GetConfigurationIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationIdResponse> CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap.GetConfigurationIdAsync(CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationIdRequest request) {
            return base.Channel.GetConfigurationIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationIdResponse> GetConfigurationIdAsync(long controlpointid) {
            CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationIdRequest inValue = new CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationIdRequest();
            inValue.Body = new CacheNomAdministration.SoapServices.SoapProxy.GetConfigurationIdRequestBody();
            inValue.Body.controlpointid = controlpointid;
            return ((CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap)(this)).GetConfigurationIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CacheNomAdministration.SoapServices.SoapProxy.GetIdControlPointResponse CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap.GetIdControlPoint(CacheNomAdministration.SoapServices.SoapProxy.GetIdControlPointRequest request) {
            return base.Channel.GetIdControlPoint(request);
        }
        
        public CacheNomAdministration.SoapServices.SoapProxy.ArrayOfMeasuringPointsMeasuringPoints GetIdControlPoint() {
            CacheNomAdministration.SoapServices.SoapProxy.GetIdControlPointRequest inValue = new CacheNomAdministration.SoapServices.SoapProxy.GetIdControlPointRequest();
            inValue.Body = new CacheNomAdministration.SoapServices.SoapProxy.GetIdControlPointRequestBody();
            CacheNomAdministration.SoapServices.SoapProxy.GetIdControlPointResponse retVal = ((CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap)(this)).GetIdControlPoint(inValue);
            return retVal.Body.GetIdControlPointResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CacheNomAdministration.SoapServices.SoapProxy.GetIdControlPointResponse> CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap.GetIdControlPointAsync(CacheNomAdministration.SoapServices.SoapProxy.GetIdControlPointRequest request) {
            return base.Channel.GetIdControlPointAsync(request);
        }
        
        public System.Threading.Tasks.Task<CacheNomAdministration.SoapServices.SoapProxy.GetIdControlPointResponse> GetIdControlPointAsync() {
            CacheNomAdministration.SoapServices.SoapProxy.GetIdControlPointRequest inValue = new CacheNomAdministration.SoapServices.SoapProxy.GetIdControlPointRequest();
            inValue.Body = new CacheNomAdministration.SoapServices.SoapProxy.GetIdControlPointRequestBody();
            return ((CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap)(this)).GetIdControlPointAsync(inValue);
        }
        
        public bool IsValidControlPointID(long controlpointid) {
            return base.Channel.IsValidControlPointID(controlpointid);
        }
        
        public System.Threading.Tasks.Task<bool> IsValidControlPointIDAsync(long controlpointid) {
            return base.Channel.IsValidControlPointIDAsync(controlpointid);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CacheNomAdministration.SoapServices.SoapProxy.IsValidControlPointNameResponse CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap.IsValidControlPointName(CacheNomAdministration.SoapServices.SoapProxy.IsValidControlPointNameRequest request) {
            return base.Channel.IsValidControlPointName(request);
        }
        
        public bool IsValidControlPointName(long controlpointid, string controlpointname) {
            CacheNomAdministration.SoapServices.SoapProxy.IsValidControlPointNameRequest inValue = new CacheNomAdministration.SoapServices.SoapProxy.IsValidControlPointNameRequest();
            inValue.Body = new CacheNomAdministration.SoapServices.SoapProxy.IsValidControlPointNameRequestBody();
            inValue.Body.controlpointid = controlpointid;
            inValue.Body.controlpointname = controlpointname;
            CacheNomAdministration.SoapServices.SoapProxy.IsValidControlPointNameResponse retVal = ((CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap)(this)).IsValidControlPointName(inValue);
            return retVal.Body.IsValidControlPointNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CacheNomAdministration.SoapServices.SoapProxy.IsValidControlPointNameResponse> CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap.IsValidControlPointNameAsync(CacheNomAdministration.SoapServices.SoapProxy.IsValidControlPointNameRequest request) {
            return base.Channel.IsValidControlPointNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<CacheNomAdministration.SoapServices.SoapProxy.IsValidControlPointNameResponse> IsValidControlPointNameAsync(long controlpointid, string controlpointname) {
            CacheNomAdministration.SoapServices.SoapProxy.IsValidControlPointNameRequest inValue = new CacheNomAdministration.SoapServices.SoapProxy.IsValidControlPointNameRequest();
            inValue.Body = new CacheNomAdministration.SoapServices.SoapProxy.IsValidControlPointNameRequestBody();
            inValue.Body.controlpointid = controlpointid;
            inValue.Body.controlpointname = controlpointname;
            return ((CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap)(this)).IsValidControlPointNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CacheNomAdministration.SoapServices.SoapProxy.IsValidProductCodeResponse CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap.IsValidProductCode(CacheNomAdministration.SoapServices.SoapProxy.IsValidProductCodeRequest request) {
            return base.Channel.IsValidProductCode(request);
        }
        
        public bool IsValidProductCode(string productcode) {
            CacheNomAdministration.SoapServices.SoapProxy.IsValidProductCodeRequest inValue = new CacheNomAdministration.SoapServices.SoapProxy.IsValidProductCodeRequest();
            inValue.Body = new CacheNomAdministration.SoapServices.SoapProxy.IsValidProductCodeRequestBody();
            inValue.Body.productcode = productcode;
            CacheNomAdministration.SoapServices.SoapProxy.IsValidProductCodeResponse retVal = ((CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap)(this)).IsValidProductCode(inValue);
            return retVal.Body.IsValidProductCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CacheNomAdministration.SoapServices.SoapProxy.IsValidProductCodeResponse> CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap.IsValidProductCodeAsync(CacheNomAdministration.SoapServices.SoapProxy.IsValidProductCodeRequest request) {
            return base.Channel.IsValidProductCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CacheNomAdministration.SoapServices.SoapProxy.IsValidProductCodeResponse> IsValidProductCodeAsync(string productcode) {
            CacheNomAdministration.SoapServices.SoapProxy.IsValidProductCodeRequest inValue = new CacheNomAdministration.SoapServices.SoapProxy.IsValidProductCodeRequest();
            inValue.Body = new CacheNomAdministration.SoapServices.SoapProxy.IsValidProductCodeRequestBody();
            inValue.Body.productcode = productcode;
            return ((CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap)(this)).IsValidProductCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CacheNomAdministration.SoapServices.SoapProxy.TestResponse CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap.Test(CacheNomAdministration.SoapServices.SoapProxy.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        public string Test() {
            CacheNomAdministration.SoapServices.SoapProxy.TestRequest inValue = new CacheNomAdministration.SoapServices.SoapProxy.TestRequest();
            inValue.Body = new CacheNomAdministration.SoapServices.SoapProxy.TestRequestBody();
            CacheNomAdministration.SoapServices.SoapProxy.TestResponse retVal = ((CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap)(this)).Test(inValue);
            return retVal.Body.TestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CacheNomAdministration.SoapServices.SoapProxy.TestResponse> CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap.TestAsync(CacheNomAdministration.SoapServices.SoapProxy.TestRequest request) {
            return base.Channel.TestAsync(request);
        }
        
        public System.Threading.Tasks.Task<CacheNomAdministration.SoapServices.SoapProxy.TestResponse> TestAsync() {
            CacheNomAdministration.SoapServices.SoapProxy.TestRequest inValue = new CacheNomAdministration.SoapServices.SoapProxy.TestRequest();
            inValue.Body = new CacheNomAdministration.SoapServices.SoapProxy.TestRequestBody();
            return ((CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap)(this)).TestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CacheNomAdministration.SoapServices.SoapProxy.UpdateRecordTagResponse CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap.UpdateRecordTag(CacheNomAdministration.SoapServices.SoapProxy.UpdateRecordTagRequest request) {
            return base.Channel.UpdateRecordTag(request);
        }
        
        public string UpdateRecordTag(string tag, long controlpointid, long flowdirection, long controlecode, long positionnumber, string productcode, string engineeringunit) {
            CacheNomAdministration.SoapServices.SoapProxy.UpdateRecordTagRequest inValue = new CacheNomAdministration.SoapServices.SoapProxy.UpdateRecordTagRequest();
            inValue.Body = new CacheNomAdministration.SoapServices.SoapProxy.UpdateRecordTagRequestBody();
            inValue.Body.tag = tag;
            inValue.Body.controlpointid = controlpointid;
            inValue.Body.flowdirection = flowdirection;
            inValue.Body.controlecode = controlecode;
            inValue.Body.positionnumber = positionnumber;
            inValue.Body.productcode = productcode;
            inValue.Body.engineeringunit = engineeringunit;
            CacheNomAdministration.SoapServices.SoapProxy.UpdateRecordTagResponse retVal = ((CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap)(this)).UpdateRecordTag(inValue);
            return retVal.Body.UpdateRecordTagResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CacheNomAdministration.SoapServices.SoapProxy.UpdateRecordTagResponse> CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap.UpdateRecordTagAsync(CacheNomAdministration.SoapServices.SoapProxy.UpdateRecordTagRequest request) {
            return base.Channel.UpdateRecordTagAsync(request);
        }
        
        public System.Threading.Tasks.Task<CacheNomAdministration.SoapServices.SoapProxy.UpdateRecordTagResponse> UpdateRecordTagAsync(string tag, long controlpointid, long flowdirection, long controlecode, long positionnumber, string productcode, string engineeringunit) {
            CacheNomAdministration.SoapServices.SoapProxy.UpdateRecordTagRequest inValue = new CacheNomAdministration.SoapServices.SoapProxy.UpdateRecordTagRequest();
            inValue.Body = new CacheNomAdministration.SoapServices.SoapProxy.UpdateRecordTagRequestBody();
            inValue.Body.tag = tag;
            inValue.Body.controlpointid = controlpointid;
            inValue.Body.flowdirection = flowdirection;
            inValue.Body.controlecode = controlecode;
            inValue.Body.positionnumber = positionnumber;
            inValue.Body.productcode = productcode;
            inValue.Body.engineeringunit = engineeringunit;
            return ((CacheNomAdministration.SoapServices.SoapProxy.ManagementNomenclaturesSoap)(this)).UpdateRecordTagAsync(inValue);
        }
    }
}
